### PR TITLE
Selectors and tests

### PR DESCRIPTION
**Pull request by hurrymaplelad**
Adds support for `#id.class` style selectors in tag functions.  Pulled in most of the tests from gradus/coffeecup (no coffeescript or stylus tags yet).  Added missing minor features like `comment` and `ie` tags.

UPDATE: features replaced, see below

~~Check out [test/templates](/hurrymaplelad/drykup/blob/master/test/templates.coffee) for a few candidate conventions for referencing tags from template functions.~~

~~Check out [test/include](/hurrymaplelad/drykup/blob/master/test/include.coffee) for a potential helper inclusion strategy.~~

~~Check out [test/render](/hurrymaplelad/drykup/blob/master/test/render.coffee) for an alternative to coffeecup's `cede`~~

### CODE REVIEW

**Comment by randypuro** [comment]
Hey Adam- super psyched you're tackling this! I think all of your ideas
would work fine.

I have a few far out ideas which I'm not sure anyone would be into, but
which I reckon at least merit consideration. I'm not attached to them
though, and would be happy with the more conventional path. Regardless,
it's a step up from what we're doing now.

It'd be interesting in ditching the render functionality.

I'm sure some like the distinction (and perhaps barriers) between template
code, and regular code, but to me, it's actually relatively confusing,
especially when it's all coffeescript. And since drykup closes that gap
part way, I reckon, why not close it entirely.

I think it'd be neat if any of the tag functions basically checked if there
was an existing context (htmlOut). If there was, it would simply write to
that context (as it does now). If there wasn't, it would create a context,
write to it, and then return it (while removing the context). Thus, the
outermost call into tag functions would always simply return a string.

To my way of thinking, it's a simpler model which, except for this one bit
of magic, would operate in every way identically to other coffeescript
functions. Template parameters would be passed as function parameters. Tag
and helper methods accessed via closure scope. @ inside the function would
have no special meaning, depending entirely on calling semantics. Testing a
template is as simple as calling it. Testing a helper method which uses
tags - as simple as calling it. Breaking a template into
sub-templates/functions is identical to refactoring a normal function into
smaller pieces.

For instance, if it made sense as an organization, our current template
functions could become template objects with a collection of small template
functions which can all be tested independently, and which can call each
other using @ semantics.

Anyway, I reckon it would be relatively straightforward. I guess you'd want
to add some sort of wrapper tag for surrounding unenclosed markup, but
otherwise, functionality would be relatively similar.

Sooooo, again, just some fodder for thought.

On Sun, Nov 25, 2012 at 1:32 PM, Adam Hull notifications@github.com wrote:

> Adds support for #id.class style selectors in tag functions. Pulled in
> most of the tests from gradus/coffeecup (no coffeescript or stylus tags
> yet). Added missing minor features like comment and ie tags.
> 
> Check out test/templateshttp://hurrymaplelad/drykup/blob/master/test/templates.coffeefor a few candidate conventions for referencing tags from template
> functions.
> 
> Check out test/includehttp://hurrymaplelad/drykup/blob/master/test/include.coffeefor a potential helper inclusion strategy.
> 
> Check out test/renderhttp://hurrymaplelad/drykup/blob/master/test/render.coffeefor an alternative to coffeecup's
> 
> ## cede
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/hurrymaplelad/drykup master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/goodeggs/drykup/pull/1
> Commit Summary
> - Wire existing tests into mocha
> - Strip out shorthand attribute expansion
> - Add CSS selector support to tag functions
> - Export Drykup constructor as backwards compatible factory
> - Add static and instance render methods
> - Consistently camel-case as DryKup
> - Port coffeecup tests and add missing functionality
> - Remove pretty printing
> - Test potential usage patterns
> - Add template inclusion
> 
> File Changes
> - _A_ .gitignore (1)
> - _M_ drykup.coffee (345)
> - _M_ package.json (10)
> - _A_ test/attributes.coffee (39)
> - _M_ test/coffeekup_org-sample.coffee (89)
> - _A_ test/coffeescript.coffee (17)
> - _A_ test/comments.coffee (7)
> - _A_ test/css_selectors.coffee (23)
> - _A_ test/custom.coffee (13)
> - _A_ test/doctype.coffee (16)
> - _A_ test/escaping.coffee (8)
> - _D_ test/expand.coffee (53)
> - _M_ test/hello-world.coffee (14)
> - _A_ test/heredocs.coffee (11)
> - _A_ test/ie_conditionals.coffee (9)
> - _A_ test/include.coffee (17)
> - _A_ test/mocha.opts (1)
> - _A_ test/render.coffee (20)
> - _A_ test/selfclosing.coffee (19)
> - _A_ test/templates.coffee (55)
> - _A_ test/text.coffee (7)
> - _A_ test/vars.coffee (15)
> 
> Patch Links
> - https://github.com/goodeggs/drykup/pull/1.patch
> - https://github.com/goodeggs/drykup/pull/1.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/goodeggs/drykup/pull/1.

## 

randy puro || good eggs || 415.857.5401

dig in: twitter http://twitter.com/goodeggs ||
facebookhttp://facebook.com/goodeggs
 || blog http://blog.goodeggs.com/

**Comment by hurrymaplelad** [comment]
Sounds clean!  Two questions:

Does this strategy imply a single global instance of DryKup that helpers share with view templates?

Would we still need a `cede`/`render` to write an HTML string within a template function?

**Comment by hurrymaplelad** [comment]
It's done!  The only hiccup I found was  [sibling root tag calls in a template function](/hurrymaplelad/drykup/blob/master/test/gotcha.coffee).

There's [a possible solution in test/fragment](/hurrymaplelad/drykup/blob/master/test/fragment.coffee).

I added a shortcut [tag module](/hurrymaplelad/drykup/blob/master/tags.coffee) that could be required as `drykup/tags` to simplify sharing a single context.  It's used throughout the tests.  We could always explicitly create another DryKup instance if we needed a separate context.

Thoughts?

**Comment by hurrymaplelad** [comment]
Alright guys, I think we nailed it.  Templates (and plain ol' tags) are not directly callable unless passed through the [`renderable` decorator](/hurrymaplelad/drykup/blob/master/test/renderable.coffee).  You can avoid the `renderable` decorator altogether by passing your template to `render` (an alias of `cede`).  Or you can mix and match up a rainy San Francisco windstorm of template functions.  Compostions of `render` and `renderable` deliver all my favorite use cases:
- `render` within a `renderable` template lets you build short strings for substitution
- calling a `renderable` within a `renderable` writes to the root template's stream
- as does calling a `renderable` within a `render`
- or calling an undecorated template within `render` or a `renderable`
- calling `render` within `render` lets you stack rendering contexts 

If everyone's comfortable trying this direction, I'm ready to rename this repo, scrub it down, and pull it into garbanzo.  Thoughts?

**Comment by randypuro** [comment]
I'm psyched!

On Wed, Nov 28, 2012 at 3:37 AM, Adam Hull notifications@github.com wrote:

> Alright guys, I think we nailed it. Templates (and plain ol' tags) are not
> directly callable unless passed through the renderable decoratorhttp://hurrymaplelad/drykup/blob/master/test/renderable.coffee.
> You can avoid the renderable decorator altogether by passing your
> template to render (an alias of cede). Or you can mix and match up a
> rainy San Francisco windstorm of template functions. Compostions of renderand
> renderable deliver all my favorite use cases:
> - render within a renderable template lets you build short strings for
>   substitution
> - calling a renderable within a renderable writes to the root
>   template's stream
> - as does calling a renderable within a render
> - or calling an undecorated template within render or a renderable
> - calling render within render lets you stack rendering contexts
> 
> If everyone's comfortable trying this direction, I'm ready to rename this
> repo, scrub it down, and pull it into garbanzo. Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/goodeggs/drykup/pull/1#issuecomment-10799574.

## 

randy puro || good eggs || 415.857.5401

dig in: twitter http://twitter.com/goodeggs ||
facebookhttp://facebook.com/goodeggs
 || blog http://blog.goodeggs.com/

**Pull request closed without merging**
